/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "adminAdjustReputation"
      | "agentCount"
      | "agents"
      | "findAgentsByCapability"
      | "heartbeat"
      | "isLive"
      | "registerAgent"
      | "reputation"
      | "submitTaskCompletion"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AgentHeartbeat"
      | "AgentRegistered"
      | "AgentUpdated"
      | "TaskCompleted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "adminAdjustReputation",
    values: [AddressLike, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "agentCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "agents", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "findAgentsByCapability",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "heartbeat", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isLive",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, BytesLike, string[], string]
  ): string;
  encodeFunctionData(
    functionFragment: "reputation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitTaskCompletion",
    values: [BytesLike, string, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "adminAdjustReputation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "agentCount", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "findAgentsByCapability",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "heartbeat", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isLive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reputation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitTaskCompletion",
    data: BytesLike
  ): Result;
}

export namespace AgentHeartbeatEvent {
  export type InputTuple = [agent: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [agent: string, timestamp: bigint];
  export interface OutputObject {
    agent: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [
    agent: AddressLike,
    owner: AddressLike,
    name: string,
    endpoint: string,
    codeHash: BytesLike
  ];
  export type OutputTuple = [
    agent: string,
    owner: string,
    name: string,
    endpoint: string,
    codeHash: string
  ];
  export interface OutputObject {
    agent: string;
    owner: string;
    name: string;
    endpoint: string;
    codeHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AgentUpdatedEvent {
  export type InputTuple = [agent: AddressLike, name: string, endpoint: string];
  export type OutputTuple = [agent: string, name: string, endpoint: string];
  export interface OutputObject {
    agent: string;
    name: string;
    endpoint: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TaskCompletedEvent {
  export type InputTuple = [
    taskId: BytesLike,
    agent: AddressLike,
    outcome: string,
    scoreDelta: BigNumberish,
    reason: string
  ];
  export type OutputTuple = [
    taskId: string,
    agent: string,
    outcome: string,
    scoreDelta: bigint,
    reason: string
  ];
  export interface OutputObject {
    taskId: string;
    agent: string;
    outcome: string;
    scoreDelta: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  adminAdjustReputation: TypedContractMethod<
    [agent: AddressLike, category: string, delta: BigNumberish],
    [void],
    "nonpayable"
  >;

  agentCount: TypedContractMethod<[], [bigint], "view">;

  agents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, bigint, bigint, boolean] & {
        owner: string;
        name: string;
        endpoint: string;
        codeHash: string;
        metadataURI: string;
        registeredAt: bigint;
        lastHeartbeat: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  findAgentsByCapability: TypedContractMethod<
    [capability: string],
    [string[]],
    "view"
  >;

  heartbeat: TypedContractMethod<[], [void], "nonpayable">;

  isLive: TypedContractMethod<
    [agent: AddressLike, windowSec: BigNumberish],
    [boolean],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [
      name: string,
      endpoint: string,
      codeHash: BytesLike,
      capabilities: string[],
      metadataURI: string
    ],
    [string],
    "nonpayable"
  >;

  reputation: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        reliability: bigint;
        speed: bigint;
        quality: bigint;
        cost: bigint;
      }
    ],
    "view"
  >;

  submitTaskCompletion: TypedContractMethod<
    [
      taskId: BytesLike,
      outcome: string,
      scoreDelta: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "adminAdjustReputation"
  ): TypedContractMethod<
    [agent: AddressLike, category: string, delta: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "agentCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, string, string, string, bigint, bigint, boolean] & {
        owner: string;
        name: string;
        endpoint: string;
        codeHash: string;
        metadataURI: string;
        registeredAt: bigint;
        lastHeartbeat: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "findAgentsByCapability"
  ): TypedContractMethod<[capability: string], [string[]], "view">;
  getFunction(
    nameOrSignature: "heartbeat"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isLive"
  ): TypedContractMethod<
    [agent: AddressLike, windowSec: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [
      name: string,
      endpoint: string,
      codeHash: BytesLike,
      capabilities: string[],
      metadataURI: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "reputation"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint, bigint] & {
        reliability: bigint;
        speed: bigint;
        quality: bigint;
        cost: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitTaskCompletion"
  ): TypedContractMethod<
    [
      taskId: BytesLike,
      outcome: string,
      scoreDelta: BigNumberish,
      reason: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentHeartbeat"
  ): TypedContractEvent<
    AgentHeartbeatEvent.InputTuple,
    AgentHeartbeatEvent.OutputTuple,
    AgentHeartbeatEvent.OutputObject
  >;
  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "AgentUpdated"
  ): TypedContractEvent<
    AgentUpdatedEvent.InputTuple,
    AgentUpdatedEvent.OutputTuple,
    AgentUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TaskCompleted"
  ): TypedContractEvent<
    TaskCompletedEvent.InputTuple,
    TaskCompletedEvent.OutputTuple,
    TaskCompletedEvent.OutputObject
  >;

  filters: {
    "AgentHeartbeat(address,uint256)": TypedContractEvent<
      AgentHeartbeatEvent.InputTuple,
      AgentHeartbeatEvent.OutputTuple,
      AgentHeartbeatEvent.OutputObject
    >;
    AgentHeartbeat: TypedContractEvent<
      AgentHeartbeatEvent.InputTuple,
      AgentHeartbeatEvent.OutputTuple,
      AgentHeartbeatEvent.OutputObject
    >;

    "AgentRegistered(address,address,string,string,bytes32)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "AgentUpdated(address,string,string)": TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;
    AgentUpdated: TypedContractEvent<
      AgentUpdatedEvent.InputTuple,
      AgentUpdatedEvent.OutputTuple,
      AgentUpdatedEvent.OutputObject
    >;

    "TaskCompleted(bytes32,address,string,int256,string)": TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
    TaskCompleted: TypedContractEvent<
      TaskCompletedEvent.InputTuple,
      TaskCompletedEvent.OutputTuple,
      TaskCompletedEvent.OutputObject
    >;
  };
}
